# Generated by Django 3.2.4 on 2021-06-05 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('groupname', models.CharField(help_text='please, specify the nameof group', max_length=100, primary_key=True, serialize=False)),
                ('groupinfo', models.TextField(help_text='please, specify additional info if required')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='any Name is OK here', max_length=100)),
                ('phone', models.CharField(help_text='any phone-number is OK here', max_length=11)),
                ('mailbox', models.EmailField(help_text='email address with @ required', max_length=100)),
                ('group', models.ForeignKey(help_text='need to define group', on_delete=django.db.models.deletion.CASCADE, to='PhoneBook2.workgroup')),
            ],
        ),
    ]
