# Generated by Django 3.2.4 on 2021-06-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneBook2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRecordWithGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='any Name is OK here', max_length=100)),
                ('phone', models.CharField(help_text='any phone-number is OK here', max_length=11)),
                ('mailbox', models.EmailField(help_text='email address with @ required', max_length=100)),
                ('group', models.CharField(choices=[('home', 'home group'), ('work', 'work group'), ('others', 'all other contact')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroupSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(choices=[('home', 'home group'), ('work', 'work group'), ('others', 'all other contact')], max_length=20)),
            ],
        ),
    ]
